name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Print npm debug log if npm ci fails
        if: failure()
        run: cat /home/runner/.npm/_logs/*-debug.log

      - name: Run CI script
        run: npm run ci

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Push Docker image
        run: docker push my-app

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml

      - name: Deploy to AWS CodeDeploy
        run: aws deploy create-deployment --application-name MyApp --deployment-group-name MyDeploymentGroup --github-location repository=my-repo,commitId=$GITHUB_SHA

      - name: Monitor CI/CD pipeline
        run: |
          echo "Monitoring CI/CD pipeline using GitHub Actions, notifications, logs and artifacts, third-party tools, and manual checks."
